# Generated by Django 5.1.4 on 2025-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff')], default='user', max_length=10),
            preserve_default=False,
        ),
    ]
